### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by rayanmargham** [FraserLee/bevy_sprite3d#5]
What's the Error? when attempting to spawn a sprite3d and upon calling bundle this line of code panics:
`let image_size = params.images.get(&self.image).unwrap().texture_descriptor.size;`
however bevy is able to load the image just fine.
here's my full code.
```

use bevy::prelude::*;
use bevy_inspector_egui::quick::WorldInspectorPlugin;
use bevy_sprite3d::Sprite3d;
use bevy_sprite3d::*;
use std::sync::Mutex;
use kira::{
	manager::{
		AudioManager, AudioManagerSettings,
		backend::cpal::CpalBackend,
	},
	sound::streaming::{StreamingSoundData, StreamingSoundSettings},
};
#[derive(Resource)]
struct Epic
{
    manager: Mutex<AudioManager>
}

fn main() {
    let mut manager = Epic { manager: AudioManager::<CpalBackend>::new(AudioManagerSettings::default()).unwrap().into()};
    App::new()
        .insert_resource(manager)
        .add_plugins(DefaultPlugins)
        .add_plugin(Sprite3dPlugin)
        .add_plugin(WorldInspectorPlugin::new())
        .add_startup_system(setup)
        .run();
}

fn setup(mut manager: ResMut<Epic>, mut commands: Commands,  asset_server: Res<AssetServer>,  mut sprite_params : Sprite3dParams) 
{
    println!("do something");
    
    let sound_data = StreamingSoundData::from_file("assets/audio/isle.mp3", StreamingSoundSettings::default()).unwrap();

    manager.manager.lock().unwrap().play(sound_data).unwrap();
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(0.0, 0.0, 0.0),
        ..default()
    });
    let image = asset_server.load("bf.png");
    
    commands.spawn(Sprite3d
    {
        image: image,
        unlit: true,
        ..default()
    }.bundle(&mut sprite_params));
}
```

**Comment by rayanmargham** [comment]
Please respond ASAP, I need this plugin for a project

**Comment by FraserLee** [comment]
`asset_server.load("bf.png");` doesn't immediately load the image, instead it queues all assets to load in the background. At the point that you call `.bundle(&mut sprite_params));` bevy_sprite3d needs the image to be loaded in order to construct the mesh. To fix this either add a loading stage as shown in [examples/sprite.rs](https://github.com/FraserLee/bevy_sprite3d/blob/main/examples/sprite.rs) or use bevy asset loader as shown in [examples/bevy_asset_loader/sprite.rs](https://github.com/FraserLee/bevy_sprite3d/blob/main/examples/bevy_asset_loader/sprite.rs) *(this example isn't yet updated to 0.10, though the changes are pretty minor)*.

More info:
https://github.com/FraserLee/bevy_sprite3d/blob/main/readme.md?plain=1#L92-L98
https://docs.rs/bevy/latest/bevy/asset/struct.AssetServer.html#method.load
https://bevy-cheatbook.github.io/assets/assetserver.html

I'm cramming for finals rn, will look into adding a more informative error message when I get a sec. Message if you need any help though I might not respond for a while. Good luck!
